### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by pvliss** [jhipster/react-jhipster#24]
We need to update dependencies where appropriate to match those used by React apps at the parent JHipster project in order to avoid any issues. 

See https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/react/package.json.ejs

Related Issues:
- https://github.com/jhipster/generator-jhipster/pull/9336
- https://github.com/jhipster/generator-jhipster/pull/9444

NOTE: The `react-addons-css-transition-group` and `react-addons-transition-group` have been deprecated and replaced by `react-transition-group`. For the generator this was done in https://github.com/jhipster/generator-jhipster/commit/1b58c249439a626dfb631583ecb1cd2378a85612

**Comment by pascalgrimaud** [comment]
When using `npm audit`, there are a lot of vulnerabilities:

```
found 522 vulnerabilities (35 low, 463 moderate, 24 high) in 33232 scanned packages
  run `npm audit fix` to fix 92 of them.
  430 vulnerabilities require semver-major dependency updates.
```
