### ISSUE TITLE
Support IE11 - entity view

### ISSUE THREAD

**Issue by CatMonster** [jhipster/react-jhipster#41]
Hi, after babel transpiling and polyfilling, I get this error on IE11 on the entity page.
![image](https://user-images.githubusercontent.com/13244343/72553971-16641c00-389a-11ea-9d19-bebd58e60104.png)

![image](https://user-images.githubusercontent.com/13244343/72553650-760df780-3899-11ea-9ddf-02899aa9a4cd.png)

This error appens when getEntity method is called inside entity reducer: when request url with sorting, page size and page number is enabled cause this issue.
Any support please.

**Comment by ruddell** [comment]
Have you tried following the tip for enabling IE support?  It requires adding some polyfills https://www.jhipster.tech/tips/028_tip_ie_support.html

**Comment by CatMonster** [comment]
Tried a couple of days after its release and wasn't working, some files does not even exists inside my project

**Comment by CatMonster** [comment]
Fixed with polyfilli.io URL - https://polyfill.io/v3/polyfill.min.js?features=URL
